# coding: utf-8

"""
    Codebeamer swagger API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.choice_option_reference import ChoiceOptionReference  # noqa: E501
from swagger_client.rest import ApiException


class TestChoiceOptionReference(unittest.TestCase):
    """ChoiceOptionReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChoiceOptionReference(self):
        """Test ChoiceOptionReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.choice_option_reference.ChoiceOptionReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
