# coding: utf-8

"""
    Codebeamer swagger API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.auto_apply_test_step_reuses import AutoApplyTestStepReuses  # noqa: E501
from swagger_client.rest import ApiException


class TestAutoApplyTestStepReuses(unittest.TestCase):
    """AutoApplyTestStepReuses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAutoApplyTestStepReuses(self):
        """Test AutoApplyTestStepReuses"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.auto_apply_test_step_reuses.AutoApplyTestStepReuses()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
