# coding: utf-8

"""
    Codebeamer swagger API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.migration_api import MigrationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMigrationApi(unittest.TestCase):
    """MigrationApi unit test stubs"""

    def setUp(self):
        self.api = MigrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_migrate_attachments(self):
        """Test case for migrate_attachments

        Migrate attachments  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
