# coding: utf-8

"""
    Codebeamer swagger API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tracker_report_api import TrackerReportApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTrackerReportApi(unittest.TestCase):
    """TrackerReportApi unit test stubs"""

    def setUp(self):
        self.api = TrackerReportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_tracker_report(self):
        """Test case for create_tracker_report

        Creates a report of a specific tracker  # noqa: E501
        """
        pass

    def test_delete_tracker_report(self):
        """Test case for delete_tracker_report

        Deletes a report of a specific tracker  # noqa: E501
        """
        pass

    def test_get_tracker_report(self):
        """Test case for get_tracker_report

        Get a report of a specific tracker  # noqa: E501
        """
        pass

    def test_get_tracker_report_items(self):
        """Test case for get_tracker_report_items

        Get report items of a specific tracker view  # noqa: E501
        """
        pass

    def test_get_tracker_reports(self):
        """Test case for get_tracker_reports

        Get all reports of a specific tracker  # noqa: E501
        """
        pass

    def test_update_tracker_report(self):
        """Test case for update_tracker_report

        Updates a report of a specific tracker  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
