# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.resource_unauthorized_exception import ResourceUnauthorizedException

class TestResourceUnauthorizedException(unittest.TestCase):
    """ResourceUnauthorizedException unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceUnauthorizedException:
        """Test ResourceUnauthorizedException
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceUnauthorizedException`
        """
        model = ResourceUnauthorizedException()
        if include_optional:
            return ResourceUnauthorizedException(
                message = '',
                resource_uri = ''
            )
        else:
            return ResourceUnauthorizedException(
        )
        """

    def testResourceUnauthorizedException(self):
        """Test ResourceUnauthorizedException"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
