# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dependency_finder_job_status_info import DependencyFinderJobStatusInfo

class TestDependencyFinderJobStatusInfo(unittest.TestCase):
    """DependencyFinderJobStatusInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DependencyFinderJobStatusInfo:
        """Test DependencyFinderJobStatusInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DependencyFinderJobStatusInfo`
        """
        model = DependencyFinderJobStatusInfo()
        if include_optional:
            return DependencyFinderJobStatusInfo(
                closed_project_warnings = [
                    ''
                    ],
                dependencies = [
                    openapi_client.models.cross_project_dependency.CrossProjectDependency(
                        referred_from = [
                            openapi_client.models.dependency_attribute.DependencyAttribute(
                                lookup_direction = 'Forward', 
                                path = [
                                    openapi_client.models.dependency_entity_reference.DependencyEntityReference()
                                    ], )
                            ], 
                        source_project = openapi_client.models.project_reference.ProjectReference(), 
                        target_project = openapi_client.models.project_reference.ProjectReference(), )
                    ],
                missing_permission_warnings = [
                    ''
                    ],
                projects_checked = 56,
                projects_scheduled = 56
            )
        else:
            return DependencyFinderJobStatusInfo(
        )
        """

    def testDependencyFinderJobStatusInfo(self):
        """Test DependencyFinderJobStatusInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
