# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.choice_field_multi_value import ChoiceFieldMultiValue

class TestChoiceFieldMultiValue(unittest.TestCase):
    """ChoiceFieldMultiValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChoiceFieldMultiValue:
        """Test ChoiceFieldMultiValue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChoiceFieldMultiValue`
        """
        model = ChoiceFieldMultiValue()
        if include_optional:
            return ChoiceFieldMultiValue(
                multiple_selection = True,
                values = [
                    openapi_client.models.abstract_reference.AbstractReference(
                        id = 0, 
                        name = '', )
                    ]
            )
        else:
            return ChoiceFieldMultiValue(
        )
        """

    def testChoiceFieldMultiValue(self):
        """Test ChoiceFieldMultiValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
