# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.baseline_api import BaselineApi


class TestBaselineApi(unittest.TestCase):
    """BaselineApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BaselineApi()

    def tearDown(self) -> None:
        pass

    def test_create_baseline(self) -> None:
        """Test case for create_baseline

        Create a project or tracker baseline
        """
        pass


if __name__ == '__main__':
    unittest.main()
