# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.export_project import ExportProject

class TestExportProject(unittest.TestCase):
    """ExportProject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExportProject:
        """Test ExportProject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExportProject`
        """
        model = ExportProject()
        if include_optional:
            return ExportProject(
                password = '007',
                selected_tracker_ids = [
                    56
                    ],
                skip_associations = True,
                skip_reports = True,
                skip_tracker_items = True,
                skip_wiki_pages = True
            )
        else:
            return ExportProject(
        )
        """

    def testExportProject(self):
        """Test ExportProject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
