# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.tracker_report_api import TrackerReportApi


class TestTrackerReportApi(unittest.TestCase):
    """TrackerReportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TrackerReportApi()

    def tearDown(self) -> None:
        pass

    def test_create_tracker_report(self) -> None:
        """Test case for create_tracker_report

        Creates a report of a specific tracker
        """
        pass

    def test_delete_tracker_report(self) -> None:
        """Test case for delete_tracker_report

        Deletes a report of a specific tracker
        """
        pass

    def test_get_tracker_report(self) -> None:
        """Test case for get_tracker_report

        Get a report of a specific tracker
        """
        pass

    def test_get_tracker_report_items(self) -> None:
        """Test case for get_tracker_report_items

        Get report items of a specific tracker view
        """
        pass

    def test_get_tracker_reports(self) -> None:
        """Test case for get_tracker_reports

        Get all reports of a specific tracker
        """
        pass

    def test_update_tracker_report(self) -> None:
        """Test case for update_tracker_report

        Updates a report of a specific tracker
        """
        pass


if __name__ == '__main__':
    unittest.main()
