# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.choice_repositories import ChoiceRepositories

class TestChoiceRepositories(unittest.TestCase):
    """ChoiceRepositories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChoiceRepositories:
        """Test ChoiceRepositories
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChoiceRepositories`
        """
        model = ChoiceRepositories()
        if include_optional:
            return ChoiceRepositories(
                reference_filters = [
                    openapi_client.models.reference_filter_based_choice/reference_filter.ReferenceFilterBasedChoice.ReferenceFilter(
                        domain_id = 56, 
                        domain_type = 'TRACKER', 
                        filter_id = 56, 
                        filter_status_id = 56, 
                        id = 56, 
                        target_ids = [
                            56
                            ], 
                        target_permissions = [
                            ''
                            ], )
                    ]
            )
        else:
            return ChoiceRepositories(
        )
        """

    def testChoiceRepositories(self):
        """Test ChoiceRepositories"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
