# coding: utf-8

"""
    Codebeamer swagger API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EditComment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'attachments': 'str',
        'comment': 'str',
        'comment_format': 'str'
    }

    attribute_map = {
        'attachments': 'attachments',
        'comment': 'comment',
        'comment_format': 'commentFormat'
    }

    def __init__(self, attachments=None, comment=None, comment_format='PlainText'):  # noqa: E501
        """EditComment - a model defined in Swagger"""  # noqa: E501
        self._attachments = None
        self._comment = None
        self._comment_format = None
        self.discriminator = None
        if attachments is not None:
            self.attachments = attachments
        self.comment = comment
        if comment_format is not None:
            self.comment_format = comment_format

    @property
    def attachments(self):
        """Gets the attachments of this EditComment.  # noqa: E501

        Attachments of a comment  # noqa: E501

        :return: The attachments of this EditComment.  # noqa: E501
        :rtype: str
        """
        return self._attachments

    @attachments.setter
    def attachments(self, attachments):
        """Sets the attachments of this EditComment.

        Attachments of a comment  # noqa: E501

        :param attachments: The attachments of this EditComment.  # noqa: E501
        :type: str
        """

        self._attachments = attachments

    @property
    def comment(self):
        """Gets the comment of this EditComment.  # noqa: E501

        Text of a comment  # noqa: E501

        :return: The comment of this EditComment.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this EditComment.

        Text of a comment  # noqa: E501

        :param comment: The comment of this EditComment.  # noqa: E501
        :type: str
        """
        if comment is None:
            raise ValueError("Invalid value for `comment`, must not be `None`")  # noqa: E501

        self._comment = comment

    @property
    def comment_format(self):
        """Gets the comment_format of this EditComment.  # noqa: E501

        Format of a comment  # noqa: E501

        :return: The comment_format of this EditComment.  # noqa: E501
        :rtype: str
        """
        return self._comment_format

    @comment_format.setter
    def comment_format(self, comment_format):
        """Sets the comment_format of this EditComment.

        Format of a comment  # noqa: E501

        :param comment_format: The comment_format of this EditComment.  # noqa: E501
        :type: str
        """
        allowed_values = ["PlainText", "Html", "Wiki"]  # noqa: E501
        if comment_format not in allowed_values:
            raise ValueError(
                "Invalid value for `comment_format` ({0}), must be one of {1}"  # noqa: E501
                .format(comment_format, allowed_values)
            )

        self._comment_format = comment_format

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EditComment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EditComment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
