# coding: utf-8

"""
    Codebeamer swagger API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WikiPage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'change_comment': 'str',
        'child_pages': 'list[WikiPageReference]',
        'comments': 'list[AttachmentReference]',
        'created_at': 'datetime',
        'created_by': 'UserReference',
        'description': 'str',
        'description_format': 'str',
        'id': 'int',
        'markup': 'str',
        'modified_at': 'datetime',
        'modified_by': 'UserReference',
        'name': 'str',
        'parent': 'AbstractReference',
        'project': 'ProjectReference',
        'version': 'int'
    }

    attribute_map = {
        'change_comment': 'changeComment',
        'child_pages': 'childPages',
        'comments': 'comments',
        'created_at': 'createdAt',
        'created_by': 'createdBy',
        'description': 'description',
        'description_format': 'descriptionFormat',
        'id': 'id',
        'markup': 'markup',
        'modified_at': 'modifiedAt',
        'modified_by': 'modifiedBy',
        'name': 'name',
        'parent': 'parent',
        'project': 'project',
        'version': 'version'
    }

    def __init__(self, change_comment=None, child_pages=None, comments=None, created_at=None, created_by=None, description=None, description_format=None, id=None, markup=None, modified_at=None, modified_by=None, name=None, parent=None, project=None, version=None):  # noqa: E501
        """WikiPage - a model defined in Swagger"""  # noqa: E501
        self._change_comment = None
        self._child_pages = None
        self._comments = None
        self._created_at = None
        self._created_by = None
        self._description = None
        self._description_format = None
        self._id = None
        self._markup = None
        self._modified_at = None
        self._modified_by = None
        self._name = None
        self._parent = None
        self._project = None
        self._version = None
        self.discriminator = None
        if change_comment is not None:
            self.change_comment = change_comment
        if child_pages is not None:
            self.child_pages = child_pages
        if comments is not None:
            self.comments = comments
        if created_at is not None:
            self.created_at = created_at
        if created_by is not None:
            self.created_by = created_by
        if description is not None:
            self.description = description
        if description_format is not None:
            self.description_format = description_format
        if id is not None:
            self.id = id
        if markup is not None:
            self.markup = markup
        if modified_at is not None:
            self.modified_at = modified_at
        if modified_by is not None:
            self.modified_by = modified_by
        if name is not None:
            self.name = name
        if parent is not None:
            self.parent = parent
        if project is not None:
            self.project = project
        if version is not None:
            self.version = version

    @property
    def change_comment(self):
        """Gets the change_comment of this WikiPage.  # noqa: E501

        Summary of the changes in this wiki page version  # noqa: E501

        :return: The change_comment of this WikiPage.  # noqa: E501
        :rtype: str
        """
        return self._change_comment

    @change_comment.setter
    def change_comment(self, change_comment):
        """Sets the change_comment of this WikiPage.

        Summary of the changes in this wiki page version  # noqa: E501

        :param change_comment: The change_comment of this WikiPage.  # noqa: E501
        :type: str
        """

        self._change_comment = change_comment

    @property
    def child_pages(self):
        """Gets the child_pages of this WikiPage.  # noqa: E501

        Child pages of the current Wiki page  # noqa: E501

        :return: The child_pages of this WikiPage.  # noqa: E501
        :rtype: list[WikiPageReference]
        """
        return self._child_pages

    @child_pages.setter
    def child_pages(self, child_pages):
        """Sets the child_pages of this WikiPage.

        Child pages of the current Wiki page  # noqa: E501

        :param child_pages: The child_pages of this WikiPage.  # noqa: E501
        :type: list[WikiPageReference]
        """

        self._child_pages = child_pages

    @property
    def comments(self):
        """Gets the comments of this WikiPage.  # noqa: E501

        Comments/attachments associated with the wiki page  # noqa: E501

        :return: The comments of this WikiPage.  # noqa: E501
        :rtype: list[AttachmentReference]
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """Sets the comments of this WikiPage.

        Comments/attachments associated with the wiki page  # noqa: E501

        :param comments: The comments of this WikiPage.  # noqa: E501
        :type: list[AttachmentReference]
        """

        self._comments = comments

    @property
    def created_at(self):
        """Gets the created_at of this WikiPage.  # noqa: E501

        The date when the entity was created  # noqa: E501

        :return: The created_at of this WikiPage.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this WikiPage.

        The date when the entity was created  # noqa: E501

        :param created_at: The created_at of this WikiPage.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def created_by(self):
        """Gets the created_by of this WikiPage.  # noqa: E501


        :return: The created_by of this WikiPage.  # noqa: E501
        :rtype: UserReference
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this WikiPage.


        :param created_by: The created_by of this WikiPage.  # noqa: E501
        :type: UserReference
        """

        self._created_by = created_by

    @property
    def description(self):
        """Gets the description of this WikiPage.  # noqa: E501

        Description of the entity  # noqa: E501

        :return: The description of this WikiPage.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this WikiPage.

        Description of the entity  # noqa: E501

        :param description: The description of this WikiPage.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def description_format(self):
        """Gets the description_format of this WikiPage.  # noqa: E501

        Description format of the entity  # noqa: E501

        :return: The description_format of this WikiPage.  # noqa: E501
        :rtype: str
        """
        return self._description_format

    @description_format.setter
    def description_format(self, description_format):
        """Sets the description_format of this WikiPage.

        Description format of the entity  # noqa: E501

        :param description_format: The description_format of this WikiPage.  # noqa: E501
        :type: str
        """
        allowed_values = ["PlainText", "Html", "Wiki"]  # noqa: E501
        if description_format not in allowed_values:
            raise ValueError(
                "Invalid value for `description_format` ({0}), must be one of {1}"  # noqa: E501
                .format(description_format, allowed_values)
            )

        self._description_format = description_format

    @property
    def id(self):
        """Gets the id of this WikiPage.  # noqa: E501

        Id of the entity  # noqa: E501

        :return: The id of this WikiPage.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WikiPage.

        Id of the entity  # noqa: E501

        :param id: The id of this WikiPage.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def markup(self):
        """Gets the markup of this WikiPage.  # noqa: E501

        Content markup of the wiki page  # noqa: E501

        :return: The markup of this WikiPage.  # noqa: E501
        :rtype: str
        """
        return self._markup

    @markup.setter
    def markup(self, markup):
        """Sets the markup of this WikiPage.

        Content markup of the wiki page  # noqa: E501

        :param markup: The markup of this WikiPage.  # noqa: E501
        :type: str
        """

        self._markup = markup

    @property
    def modified_at(self):
        """Gets the modified_at of this WikiPage.  # noqa: E501

        The date when the entity was modified  # noqa: E501

        :return: The modified_at of this WikiPage.  # noqa: E501
        :rtype: datetime
        """
        return self._modified_at

    @modified_at.setter
    def modified_at(self, modified_at):
        """Sets the modified_at of this WikiPage.

        The date when the entity was modified  # noqa: E501

        :param modified_at: The modified_at of this WikiPage.  # noqa: E501
        :type: datetime
        """

        self._modified_at = modified_at

    @property
    def modified_by(self):
        """Gets the modified_by of this WikiPage.  # noqa: E501


        :return: The modified_by of this WikiPage.  # noqa: E501
        :rtype: UserReference
        """
        return self._modified_by

    @modified_by.setter
    def modified_by(self, modified_by):
        """Sets the modified_by of this WikiPage.


        :param modified_by: The modified_by of this WikiPage.  # noqa: E501
        :type: UserReference
        """

        self._modified_by = modified_by

    @property
    def name(self):
        """Gets the name of this WikiPage.  # noqa: E501

        Name of the entity  # noqa: E501

        :return: The name of this WikiPage.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WikiPage.

        Name of the entity  # noqa: E501

        :param name: The name of this WikiPage.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def parent(self):
        """Gets the parent of this WikiPage.  # noqa: E501


        :return: The parent of this WikiPage.  # noqa: E501
        :rtype: AbstractReference
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this WikiPage.


        :param parent: The parent of this WikiPage.  # noqa: E501
        :type: AbstractReference
        """

        self._parent = parent

    @property
    def project(self):
        """Gets the project of this WikiPage.  # noqa: E501


        :return: The project of this WikiPage.  # noqa: E501
        :rtype: ProjectReference
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this WikiPage.


        :param project: The project of this WikiPage.  # noqa: E501
        :type: ProjectReference
        """

        self._project = project

    @property
    def version(self):
        """Gets the version of this WikiPage.  # noqa: E501

        Version of the wiki page  # noqa: E501

        :return: The version of this WikiPage.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this WikiPage.

        Version of the wiki page  # noqa: E501

        :param version: The version of this WikiPage.  # noqa: E501
        :type: int
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WikiPage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WikiPage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
