# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.dependency_entity_reference import DependencyEntityReference  # noqa: E501
from swagger_client.rest import ApiException


class TestDependencyEntityReference(unittest.TestCase):
    """DependencyEntityReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDependencyEntityReference(self):
        """Test DependencyEntityReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.dependency_entity_reference.DependencyEntityReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
