# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.invalid_parameters_exception import InvalidParametersException  # noqa: E501
from swagger_client.rest import ApiException


class TestInvalidParametersException(unittest.TestCase):
    """InvalidParametersException unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvalidParametersException(self):
        """Test InvalidParametersException"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.invalid_parameters_exception.InvalidParametersException()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
