# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.decimal_field_value import DecimalFieldValue  # noqa: E501
from swagger_client.rest import ApiException


class TestDecimalFieldValue(unittest.TestCase):
    """DecimalFieldValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDecimalFieldValue(self):
        """Test DecimalFieldValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.decimal_field_value.DecimalFieldValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
