# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tracker_item_field_mapping_info import TrackerItemFieldMappingInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestTrackerItemFieldMappingInfo(unittest.TestCase):
    """TrackerItemFieldMappingInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrackerItemFieldMappingInfo(self):
        """Test TrackerItemFieldMappingInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tracker_item_field_mapping_info.TrackerItemFieldMappingInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
