# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.deployment_project_export_settings import DeploymentProjectExportSettings
from typing import Optional, Set
from typing_extensions import Self

class ExportForDeploymentRequest(BaseModel):
    """
    Request export for deployment
    """ # noqa: E501
    export_file_name: Optional[StrictStr] = Field(default=None, description="Name of the resulting export file (without extension).", alias="exportFileName")
    password: Optional[StrictStr] = Field(default=None, description="A password that is used during the project encryption.")
    project_settings: Optional[List[DeploymentProjectExportSettings]] = Field(default=None, description="Project settings", alias="projectSettings")
    schema_name: Optional[StrictStr] = Field(default=None, description="Name of deployment settings schema", alias="schemaName")
    schema_version: Optional[StrictStr] = Field(default=None, description="Version of deployment settings schema", alias="schemaVersion")
    __properties: ClassVar[List[str]] = ["exportFileName", "password", "projectSettings", "schemaName", "schemaVersion"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExportForDeploymentRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "schema_name",
            "schema_version",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in project_settings (list)
        _items = []
        if self.project_settings:
            for _item in self.project_settings:
                if _item:
                    _items.append(_item.to_dict())
            _dict['projectSettings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExportForDeploymentRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "exportFileName": obj.get("exportFileName"),
            "password": obj.get("password"),
            "projectSettings": [DeploymentProjectExportSettings.from_dict(_item) for _item in obj["projectSettings"]] if obj.get("projectSettings") is not None else None,
            "schemaName": obj.get("schemaName"),
            "schemaVersion": obj.get("schemaVersion")
        })
        return _obj


