# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.report_cell import ReportCell
from openapi_client.models.report_item_reference import ReportItemReference
from openapi_client.models.report_reference_level import ReportReferenceLevel
from typing import Optional, Set
from typing_extensions import Self

class ReportReferencedRow(BaseModel):
    """
    Result row having references.
    """ # noqa: E501
    cells: Optional[List[ReportCell]] = Field(default=None, description="Cells in a row.")
    is_real_result: Optional[StrictBool] = Field(default=None, description="Indicator if the item is a real query result (e.g. not an ancestor item).", alias="isRealResult")
    item_ref: Optional[ReportItemReference] = Field(default=None, alias="itemRef")
    outline_level: Optional[StrictInt] = Field(default=None, description="Item's level in the tracker outline.", alias="outlineLevel")
    references: Optional[ReportReferenceLevel] = None
    __properties: ClassVar[List[str]] = ["cells", "isRealResult", "itemRef", "outlineLevel", "references"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReportReferencedRow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in cells (list)
        _items = []
        if self.cells:
            for _item in self.cells:
                if _item:
                    _items.append(_item.to_dict())
            _dict['cells'] = _items
        # override the default output from pydantic by calling `to_dict()` of item_ref
        if self.item_ref:
            _dict['itemRef'] = self.item_ref.to_dict()
        # override the default output from pydantic by calling `to_dict()` of references
        if self.references:
            _dict['references'] = self.references.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReportReferencedRow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cells": [ReportCell.from_dict(_item) for _item in obj["cells"]] if obj.get("cells") is not None else None,
            "isRealResult": obj.get("isRealResult"),
            "itemRef": ReportItemReference.from_dict(obj["itemRef"]) if obj.get("itemRef") is not None else None,
            "outlineLevel": obj.get("outlineLevel"),
            "references": ReportReferenceLevel.from_dict(obj["references"]) if obj.get("references") is not None else None
        })
        return _obj

from openapi_client.models.report_reference_level import ReportReferenceLevel
# TODO: Rewrite to not use raise_errors
ReportReferencedRow.model_rebuild(raise_errors=False)

