# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.report_reference_level_settings import ReportReferenceLevelSettings
from openapi_client.models.resizable_report_column_settings import ResizableReportColumnSettings
from openapi_client.models.tracker_reference import TrackerReference
from typing import Optional, Set
from typing_extensions import Self

class TrackerReportSettings(BaseModel):
    """
    Settings of a report on a tracker.
    """ # noqa: E501
    cb_ql: StrictStr = Field(description="CbQL query string of the report.", alias="cbQl")
    columns: List[ResizableReportColumnSettings] = Field(description="Column definitions.")
    description: StrictStr = Field(description="Description of the report.")
    is_public: StrictBool = Field(description="Public report indicator.", alias="isPublic")
    name: StrictStr = Field(description="Name of the report.")
    reference_level_settings: Optional[List[ReportReferenceLevelSettings]] = Field(default=None, description="Reference level setting for Intelligent Table View.", alias="referenceLevelSettings")
    rendering_method: Optional[StrictStr] = Field(default=None, description="Rendering method for Intelligent Table View.", alias="renderingMethod")
    report_id: Optional[StrictInt] = Field(default=None, description="Id of a report", alias="reportId")
    show_all_children: Optional[StrictBool] = Field(default=None, description="Indicator to ability to collapse/expand all child items.", alias="showAllChildren")
    show_ancestors: Optional[StrictBool] = Field(default=None, description="Indicator to show the ancestors of a result item.", alias="showAncestors")
    show_descendants: Optional[StrictBool] = Field(default=None, description="Indicator to show the descendants of a result item.", alias="showDescendants")
    tracker: TrackerReference
    __properties: ClassVar[List[str]] = ["cbQl", "columns", "description", "isPublic", "name", "referenceLevelSettings", "renderingMethod", "reportId", "showAllChildren", "showAncestors", "showDescendants", "tracker"]

    @field_validator('rendering_method')
    def rendering_method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['disabled', 'table', 'tree']):
            raise ValueError("must be one of enum values ('disabled', 'table', 'tree')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrackerReportSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in columns (list)
        _items = []
        if self.columns:
            for _item in self.columns:
                if _item:
                    _items.append(_item.to_dict())
            _dict['columns'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in reference_level_settings (list)
        _items = []
        if self.reference_level_settings:
            for _item in self.reference_level_settings:
                if _item:
                    _items.append(_item.to_dict())
            _dict['referenceLevelSettings'] = _items
        # override the default output from pydantic by calling `to_dict()` of tracker
        if self.tracker:
            _dict['tracker'] = self.tracker.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrackerReportSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cbQl": obj.get("cbQl"),
            "columns": [ResizableReportColumnSettings.from_dict(_item) for _item in obj["columns"]] if obj.get("columns") is not None else None,
            "description": obj.get("description"),
            "isPublic": obj.get("isPublic"),
            "name": obj.get("name"),
            "referenceLevelSettings": [ReportReferenceLevelSettings.from_dict(_item) for _item in obj["referenceLevelSettings"]] if obj.get("referenceLevelSettings") is not None else None,
            "renderingMethod": obj.get("renderingMethod"),
            "reportId": obj.get("reportId"),
            "showAllChildren": obj.get("showAllChildren"),
            "showAncestors": obj.get("showAncestors"),
            "showDescendants": obj.get("showDescendants"),
            "tracker": TrackerReference.from_dict(obj["tracker"]) if obj.get("tracker") is not None else None
        })
        return _obj


