# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.project_reference import ProjectReference
from openapi_client.models.tracker_field_layout_settings import TrackerFieldLayoutSettings
from openapi_client.models.tracker_reference import TrackerReference
from openapi_client.models.tracker_type_reference import TrackerTypeReference
from openapi_client.models.user_reference import UserReference
from typing import Optional, Set
from typing_extensions import Self

class Tracker(BaseModel):
    """
    Basic properties of a codebeamer tracker
    """ # noqa: E501
    available_as_template: Optional[StrictBool] = Field(default=None, description="Indicator if the tracker can be used as a template", alias="availableAsTemplate")
    color: Optional[StrictStr] = Field(default=None, description="Color of the tracker")
    created_at: Optional[datetime] = Field(default=None, description="The date when the entity was created", alias="createdAt")
    created_by: Optional[UserReference] = Field(default=None, alias="createdBy")
    default_show_ancestor_items: StrictBool = Field(description="Default Outline should show Ancestor Items or not", alias="defaultShowAncestorItems")
    default_show_descendant_items: StrictBool = Field(description="Default Outline should show Descendant Items or not", alias="defaultShowDescendantItems")
    deleted: StrictBool = Field(description="Indicator if the tracker is deleted")
    description: Optional[StrictStr] = Field(default=None, description="Description of the entity")
    description_format: Optional[StrictStr] = Field(default=None, description="Description format of the entity", alias="descriptionFormat")
    hidden: StrictBool = Field(description="Indicator if the tracker is hidden")
    id: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Id of the entity")
    key_name: Optional[StrictStr] = Field(default=None, description="Keyname of a tracker", alias="keyName")
    modified_at: Optional[datetime] = Field(default=None, description="The date when the entity was modified", alias="modifiedAt")
    modified_by: Optional[UserReference] = Field(default=None, alias="modifiedBy")
    name: Optional[StrictStr] = Field(default=None, description="Name of the entity")
    only_workflow_can_create_new_referring_item: StrictBool = Field(description="If true, then the only way to create new referring items is through workflow actions", alias="onlyWorkflowCanCreateNewReferringItem")
    project: Optional[ProjectReference] = None
    shared_in_working_set: Optional[StrictBool] = Field(default=None, description="If the tracker is shared in a WorkingSet", alias="sharedInWorkingSet")
    template_tracker: Optional[TrackerReference] = Field(default=None, alias="templateTracker")
    tracker_field_layout_settings_model: Optional[TrackerFieldLayoutSettings] = Field(default=None, alias="trackerFieldLayoutSettingsModel")
    type: Optional[TrackerTypeReference] = None
    using_quick_transitions: StrictBool = Field(description="If true, then every transition will be executed immediately (if possible) without opening an editor for the item", alias="usingQuickTransitions")
    using_workflow: StrictBool = Field(description="Should transitions and workflow actions be available in the tracker or not", alias="usingWorkflow")
    version: Optional[StrictInt] = Field(default=None, description="Version of a tracker")
    __properties: ClassVar[List[str]] = ["availableAsTemplate", "color", "createdAt", "createdBy", "defaultShowAncestorItems", "defaultShowDescendantItems", "deleted", "description", "descriptionFormat", "hidden", "id", "keyName", "modifiedAt", "modifiedBy", "name", "onlyWorkflowCanCreateNewReferringItem", "project", "sharedInWorkingSet", "templateTracker", "trackerFieldLayoutSettingsModel", "type", "usingQuickTransitions", "usingWorkflow", "version"]

    @field_validator('description_format')
    def description_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['PlainText', 'Html', 'Wiki']):
            raise ValueError("must be one of enum values ('PlainText', 'Html', 'Wiki')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Tracker from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['createdBy'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of modified_by
        if self.modified_by:
            _dict['modifiedBy'] = self.modified_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of project
        if self.project:
            _dict['project'] = self.project.to_dict()
        # override the default output from pydantic by calling `to_dict()` of template_tracker
        if self.template_tracker:
            _dict['templateTracker'] = self.template_tracker.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tracker_field_layout_settings_model
        if self.tracker_field_layout_settings_model:
            _dict['trackerFieldLayoutSettingsModel'] = self.tracker_field_layout_settings_model.to_dict()
        # override the default output from pydantic by calling `to_dict()` of type
        if self.type:
            _dict['type'] = self.type.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Tracker from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "availableAsTemplate": obj.get("availableAsTemplate"),
            "color": obj.get("color"),
            "createdAt": obj.get("createdAt"),
            "createdBy": UserReference.from_dict(obj["createdBy"]) if obj.get("createdBy") is not None else None,
            "defaultShowAncestorItems": obj.get("defaultShowAncestorItems"),
            "defaultShowDescendantItems": obj.get("defaultShowDescendantItems"),
            "deleted": obj.get("deleted"),
            "description": obj.get("description"),
            "descriptionFormat": obj.get("descriptionFormat"),
            "hidden": obj.get("hidden"),
            "id": obj.get("id"),
            "keyName": obj.get("keyName"),
            "modifiedAt": obj.get("modifiedAt"),
            "modifiedBy": UserReference.from_dict(obj["modifiedBy"]) if obj.get("modifiedBy") is not None else None,
            "name": obj.get("name"),
            "onlyWorkflowCanCreateNewReferringItem": obj.get("onlyWorkflowCanCreateNewReferringItem"),
            "project": ProjectReference.from_dict(obj["project"]) if obj.get("project") is not None else None,
            "sharedInWorkingSet": obj.get("sharedInWorkingSet"),
            "templateTracker": TrackerReference.from_dict(obj["templateTracker"]) if obj.get("templateTracker") is not None else None,
            "trackerFieldLayoutSettingsModel": TrackerFieldLayoutSettings.from_dict(obj["trackerFieldLayoutSettingsModel"]) if obj.get("trackerFieldLayoutSettingsModel") is not None else None,
            "type": TrackerTypeReference.from_dict(obj["type"]) if obj.get("type") is not None else None,
            "usingQuickTransitions": obj.get("usingQuickTransitions"),
            "usingWorkflow": obj.get("usingWorkflow"),
            "version": obj.get("version")
        })
        return _obj


