# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateBaselineRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'name': 'str',
        'project': 'ProjectReference',
        'tracker': 'TrackerReference'
    }

    attribute_map = {
        'description': 'description',
        'name': 'name',
        'project': 'project',
        'tracker': 'tracker'
    }

    def __init__(self, description=None, name=None, project=None, tracker=None):  # noqa: E501
        """CreateBaselineRequest - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._name = None
        self._project = None
        self._tracker = None
        self.discriminator = None
        if description is not None:
            self.description = description
        self.name = name
        self.project = project
        if tracker is not None:
            self.tracker = tracker

    @property
    def description(self):
        """Gets the description of this CreateBaselineRequest.  # noqa: E501

        Description of baseline  # noqa: E501

        :return: The description of this CreateBaselineRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateBaselineRequest.

        Description of baseline  # noqa: E501

        :param description: The description of this CreateBaselineRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def name(self):
        """Gets the name of this CreateBaselineRequest.  # noqa: E501

        Name of baseline  # noqa: E501

        :return: The name of this CreateBaselineRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateBaselineRequest.

        Name of baseline  # noqa: E501

        :param name: The name of this CreateBaselineRequest.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def project(self):
        """Gets the project of this CreateBaselineRequest.  # noqa: E501


        :return: The project of this CreateBaselineRequest.  # noqa: E501
        :rtype: ProjectReference
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this CreateBaselineRequest.


        :param project: The project of this CreateBaselineRequest.  # noqa: E501
        :type: ProjectReference
        """
        if project is None:
            raise ValueError("Invalid value for `project`, must not be `None`")  # noqa: E501

        self._project = project

    @property
    def tracker(self):
        """Gets the tracker of this CreateBaselineRequest.  # noqa: E501


        :return: The tracker of this CreateBaselineRequest.  # noqa: E501
        :rtype: TrackerReference
        """
        return self._tracker

    @tracker.setter
    def tracker(self, tracker):
        """Sets the tracker of this CreateBaselineRequest.


        :param tracker: The tracker of this CreateBaselineRequest.  # noqa: E501
        :type: TrackerReference
        """

        self._tracker = tracker

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateBaselineRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateBaselineRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
