# coding: utf-8

"""
    codebeamer swagger API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WorkingSetInformation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'children': 'list[WorkingSetReference]',
        'created_at': 'datetime',
        'created_by': 'UserReference',
        'deleted': 'bool',
        'id': 'int',
        'name': 'str',
        'parent': 'WorkingSetReference',
        'project': 'ProjectReference',
        'root': 'WorkingSetReference',
        'type': 'str'
    }

    attribute_map = {
        'children': 'children',
        'created_at': 'createdAt',
        'created_by': 'createdBy',
        'deleted': 'deleted',
        'id': 'id',
        'name': 'name',
        'parent': 'parent',
        'project': 'project',
        'root': 'root',
        'type': 'type'
    }

    def __init__(self, children=None, created_at=None, created_by=None, deleted=None, id=None, name=None, parent=None, project=None, root=None, type=None):  # noqa: E501
        """WorkingSetInformation - a model defined in Swagger"""  # noqa: E501
        self._children = None
        self._created_at = None
        self._created_by = None
        self._deleted = None
        self._id = None
        self._name = None
        self._parent = None
        self._project = None
        self._root = None
        self._type = None
        self.discriminator = None
        if children is not None:
            self.children = children
        if created_at is not None:
            self.created_at = created_at
        if created_by is not None:
            self.created_by = created_by
        if deleted is not None:
            self.deleted = deleted
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if parent is not None:
            self.parent = parent
        if project is not None:
            self.project = project
        if root is not None:
            self.root = root
        if type is not None:
            self.type = type

    @property
    def children(self):
        """Gets the children of this WorkingSetInformation.  # noqa: E501

        The children of the given Working-Set  # noqa: E501

        :return: The children of this WorkingSetInformation.  # noqa: E501
        :rtype: list[WorkingSetReference]
        """
        return self._children

    @children.setter
    def children(self, children):
        """Sets the children of this WorkingSetInformation.

        The children of the given Working-Set  # noqa: E501

        :param children: The children of this WorkingSetInformation.  # noqa: E501
        :type: list[WorkingSetReference]
        """

        self._children = children

    @property
    def created_at(self):
        """Gets the created_at of this WorkingSetInformation.  # noqa: E501

        The date when the entity was created  # noqa: E501

        :return: The created_at of this WorkingSetInformation.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this WorkingSetInformation.

        The date when the entity was created  # noqa: E501

        :param created_at: The created_at of this WorkingSetInformation.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def created_by(self):
        """Gets the created_by of this WorkingSetInformation.  # noqa: E501


        :return: The created_by of this WorkingSetInformation.  # noqa: E501
        :rtype: UserReference
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this WorkingSetInformation.


        :param created_by: The created_by of this WorkingSetInformation.  # noqa: E501
        :type: UserReference
        """

        self._created_by = created_by

    @property
    def deleted(self):
        """Gets the deleted of this WorkingSetInformation.  # noqa: E501

        Is the Working-Set deleted or not  # noqa: E501

        :return: The deleted of this WorkingSetInformation.  # noqa: E501
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """Sets the deleted of this WorkingSetInformation.

        Is the Working-Set deleted or not  # noqa: E501

        :param deleted: The deleted of this WorkingSetInformation.  # noqa: E501
        :type: bool
        """

        self._deleted = deleted

    @property
    def id(self):
        """Gets the id of this WorkingSetInformation.  # noqa: E501

        Id of the entity  # noqa: E501

        :return: The id of this WorkingSetInformation.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WorkingSetInformation.

        Id of the entity  # noqa: E501

        :param id: The id of this WorkingSetInformation.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this WorkingSetInformation.  # noqa: E501

        Name of the entity  # noqa: E501

        :return: The name of this WorkingSetInformation.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WorkingSetInformation.

        Name of the entity  # noqa: E501

        :param name: The name of this WorkingSetInformation.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def parent(self):
        """Gets the parent of this WorkingSetInformation.  # noqa: E501


        :return: The parent of this WorkingSetInformation.  # noqa: E501
        :rtype: WorkingSetReference
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this WorkingSetInformation.


        :param parent: The parent of this WorkingSetInformation.  # noqa: E501
        :type: WorkingSetReference
        """

        self._parent = parent

    @property
    def project(self):
        """Gets the project of this WorkingSetInformation.  # noqa: E501


        :return: The project of this WorkingSetInformation.  # noqa: E501
        :rtype: ProjectReference
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this WorkingSetInformation.


        :param project: The project of this WorkingSetInformation.  # noqa: E501
        :type: ProjectReference
        """

        self._project = project

    @property
    def root(self):
        """Gets the root of this WorkingSetInformation.  # noqa: E501


        :return: The root of this WorkingSetInformation.  # noqa: E501
        :rtype: WorkingSetReference
        """
        return self._root

    @root.setter
    def root(self, root):
        """Sets the root of this WorkingSetInformation.


        :param root: The root of this WorkingSetInformation.  # noqa: E501
        :type: WorkingSetReference
        """

        self._root = root

    @property
    def type(self):
        """Gets the type of this WorkingSetInformation.  # noqa: E501

        Type of a referenced object  # noqa: E501

        :return: The type of this WorkingSetInformation.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this WorkingSetInformation.

        Type of a referenced object  # noqa: E501

        :param type: The type of this WorkingSetInformation.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkingSetInformation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkingSetInformation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
